# -*- coding: utf-8 -*-
"""car.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11x7_Rk3Nl_KwI1ZOzTcBrj6Lx324SLuk
"""

import pandas as pd

# =========================
# Load Dataset
# =========================
df = pd.read_csv('/content/used_car_price_prediction_1M.csv')

# =========================
# Basic Information
# =========================
print(df.head())
print(df.info())
print(df.describe())

print("\nNull Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:", df.duplicated().sum())

# =========================
# Remove Duplicates
# =========================
df = df.drop_duplicates()

print("\nDuplicate rows after removal:", df.duplicated().sum())

# =========================
# Fill Missing Values
# =========================

# Numerical Columns
numerical_cols = [
    'Mileage_kmpl',
    'Engine_CC',
    'Horsepower',
    'Registration_Age'
]

for col in numerical_cols:
    df[col] = df[col].fillna(df[col].median())

# Categorical Columns
categorical_cols = [
    'Fuel_Type',
    'Transmission',
    'Color',
    'City'
]

for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

# Binary/Categorical Columns
binary_cols = [
    'Insurance_Valid',
    'Service_History',
    'Accidents',
    'Tax_Paid',
    'Number_of_Doors',
    'Seats'
]

for col in binary_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

# Remove rows where Price is null
df = df.dropna(subset=['Price'])

print("\nNull Values After Cleaning:")
print(df.isnull().sum())

# =========================
# Brand Cleaning
# =========================

df["Brand"] = df["Brand"].str.strip()

df["Brand"] = df["Brand"].str.title()

df["Brand"] = df["Brand"].replace({
    "Bmw": "BMW"
})

print("\nUnique Brands:")
print(sorted(df["Brand"].unique()))

# =========================
# Fuel Type Cleaning
# =========================

df["Fuel_Type"] = df["Fuel_Type"].str.strip().str.lower()

fuel_mapping = {
    "diesel": "Diesel",
    "petrol": "Petrol",
    "cng": "CNG",
    "electric": "Electric",
    "electrik": "Electric",
    "hybrid": "Hybrid",
    "hybridd": "Hybrid"
}

df["Fuel_Type"] = df["Fuel_Type"].replace(fuel_mapping)

print("\nUnique Fuel Types:")
print(sorted(df["Fuel_Type"].unique()))

# =========================
# Save Cleaned Dataset
# =========================

df.to_csv("/content/cleaned_cars.csv", index=False)

print("\n✅ Cleaned dataset saved successfully.")